### PR TITLE
Use cropharvest.bands.BANDS_MAX to normalize data in train.py

### PR DESCRIPTION
**Pull request by gabrieltseng**
Addresses #14

### CODE REVIEW

**Comment by gabrieltseng** [comment]
Confirmed it works: https://gist.github.com/gabrieltseng/b1decd18812012c32a4d22064ad602bb

@ivanzvonkov , the next steps would be updating cropharvest so that we can update the dependencies here; let me know if this works for you.

**Comment by ivanzvonkov** [comment]
Yes: https://github.com/nasaharvest/cropharvest/pull/92

**Comment by ivanzvonkov** [comment]
Cropharvest is updated: https://pypi.org/project/cropharvest/

**Comment by gabrieltseng** [comment]
https://gist.github.com/gabrieltseng/1bc41e2ac366f7ccdbaad84c43c23e2a

Updated and tested again

**Pull request merged**
