### PR TITLE
Use cropharvest.BANDS_MAX to normalize values in the train script

### PR DESCRIPTION
**Pull request by gabrieltseng**
Second attempt at #28

### CODE REVIEW

**Comment by ivanzvonkov** [comment]
Could you regenerate each of the train.py's by using
```
cd buildings-example
openmapflow generate
```
And regenerating only the train.py

**Comment by gabrieltseng** [comment]
> Could you regenerate each of the train.py's by using
> 
> ```
> cd buildings-example
> openmapflow generate
> ```
> 
> And regenerating only the train.py

Updated!

**Comment by gabrieltseng** [comment]
I think they are all regenerated? It should all be in this commit: https://github.com/nasaharvest/openmapflow/pull/69/commits/b8bcbc45cba1af7ee1fa4a8d75c35e1d67c23bae

**Comment by ivanzvonkov** [comment]
Apologies, for some reason I did not see all of them earlier! Looks good!

**Review by ivanzvonkov — APPROVED** [review]

**Pull request merged**
