### PR TITLE
Add utf-8 encoding specification to writing

### PR DESCRIPTION
**Pull request by bhyeh**
Issue #122 - added utf-8 encoding specification when writing report

### CODE REVIEW

**Comment by ivanzvonkov** [comment]
Were you able to test this on a Windows machine?

**Comment by ivanzvonkov** [comment]
FYI there are Windows tests that run in CI (only on main branch), so there could be a little test implemented to make sure this doesn't happen again but not absolutely necessary.

**Comment by bhyeh** [comment]
> FYI there are Windows tests that run in CI (only on main branch), so there could be a little test implemented to make sure this doesn't happen again but not absolutely necessary.

Is this test in `ci.yaml` what you are referring to? 

https://github.com/nasaharvest/openmapflow/blob/d96c9f1f942fb03a1d085cd6a9a1e791067dc1c8/.github/workflows/ci.yaml#L54-L101

**Comment by ivanzvonkov** [comment]
Yes @bhyeh

**Review by ivanzvonkov — APPROVED** [review]

**Pull request merged**
