### PR TITLE
Added changes to profile deploy.sh file

### PR DESCRIPTION
**Pull request by Aniket-Parlikar**
Added a function that helps calculate the time elapsed in-between two commands of the deploy.sh script.

### CODE REVIEW

**Comment by Aniket-Parlikar** [comment]
@ivanzvonkov yes

**Comment by ivanzvonkov** [comment]
From the issue:
> Potential solution: Profile deployment to find out the biggest time hoggers and investigate ways of speeding up.

Profiling is only the first step. This proposed change alone does not make sense to merge as profiling the script on every run does not help with anything. Profiling only makes sense in the context of an investigation in my view. @Aniket-Parlikar let me know if you think otherwise

**Comment by Aniket-Parlikar** [comment]
@ivanzvonkov I agree with your point. The primary goal of this pull request was to profile the runtime of each command. I actually wanted to run this script on my Windows machine, however, I am getting some errors(probably due to the Windows environment), due to which I thought of testing this script as part of Github actions and analyze and investigate about the runtimes of various commands

**Comment by ivanzvonkov** [comment]
Ok, you'll need to make some changes to the Github action which uses this script to see it executed here

**Comment by Aniket-Parlikar** [comment]
Created a new PR a while back...which is regarding the similar issue as dealt with within this PR.

**Pull request closed without merging**
