### PR TITLE
Don't hardcode the expected number of input timesteps during inference

### PR DESCRIPTION
**Pull request by gabrieltseng**

### CODE REVIEW

**Comment by ivanzvonkov** [comment]
Ah, it was here too! I only looked at `load_tif()`. 
Might be a good time to update the package version and `openmapflow/Dockerfile` to use the new version of the base image. What do you think?

**Comment by gabrieltseng** [comment]
> Might be a good time to update the package version and openmapflow/Dockerfile to use the new version of the base image. What do you think?

agreed - do you want to do this all in this PR?

**Comment by ivanzvonkov** [comment]
Yes, you just need to update this line to `"0.1.6rc1"`: https://github.com/nasaharvest/openmapflow/blob/0c362778bf848fe5ad4d2d0f2ba6d32e8545e648/openmapflow/constants.py#L16

Then once merged tag the main branch with
```
git tag 0.1.6rc1
git push origin --tag
```
This will publish a new pip pre-release (rc1).
So `pip install openmapflow` will still install `0.1.5` but `pip install openmapflow==0.1.6rc1` will install the new version.
This way we can verify the new docker image works as intended before full release.

**Review by ivanzvonkov — APPROVED** [review]
LGTM after version is updated

**Pull request merged**
